// <auto-generated />
using System;
using BanDienThoai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BanDienThoai.Migrations
{
    [DbContext(typeof(BandienthoaiContext))]
    [Migration("20240321031130_BanDienThoai")]
    partial class BanDienThoai
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BanDienThoai.Data.Baiviet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Ngaydang")
                        .HasColumnType("datetime2");

                    b.Property<string>("Noidung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tieude")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("New");
                });

            modelBuilder.Entity("BanDienThoai.Data.Chitietdonhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DonhangId")
                        .HasColumnType("int");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int?>("IDDH")
                        .HasColumnType("int");

                    b.Property<int?>("IDSP")
                        .HasColumnType("int");

                    b.Property<int?>("SanphamID")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonhangId");

                    b.HasIndex("SanphamID");

                    b.ToTable("CTdonhang");
                });

            modelBuilder.Entity("BanDienThoai.Data.Chitietdonnhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int?>("HoadonnhapId")
                        .HasColumnType("int");

                    b.Property<int?>("IDDHN")
                        .HasColumnType("int");

                    b.Property<int?>("IDSP")
                        .HasColumnType("int");

                    b.Property<int?>("SanphamID")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoadonnhapId");

                    b.HasIndex("SanphamID");

                    b.ToTable("Chitietdonnhap");
                });

            modelBuilder.Entity("BanDienThoai.Data.Donhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IDKH")
                        .HasColumnType("int");

                    b.Property<int?>("KhachhangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaydat")
                        .HasColumnType("datetime2");

                    b.Property<string>("PTthanhtoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float");

                    b.Property<string>("ghichu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KhachhangId");

                    b.ToTable("Donhang");
                });

            modelBuilder.Entity("BanDienThoai.Data.Hoadonnhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("IDNCC")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaynhap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhaCungCapId")
                        .HasColumnType("int");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NhaCungCapId");

                    b.ToTable("Hoadonnhap");
                });

            modelBuilder.Entity("BanDienThoai.Data.Khachhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Khachhang");
                });

            modelBuilder.Entity("BanDienThoai.Data.LoaiSp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Loaisp");
                });

            modelBuilder.Entity("BanDienThoai.Data.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("BanDienThoai.Data.Nhanvien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Diachi")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("GioiTinh")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("BanDienThoai.Data.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mota")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("BanDienThoai.Data.Sanpham", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Danhgia")
                        .HasColumnType("int");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<double>("GiaKM")
                        .HasColumnType("float");

                    b.Property<int?>("IDLSP")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiSpID")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiSpID");

                    b.ToTable("Sanpham");
                });

            modelBuilder.Entity("BanDienThoai.Data.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Loaiquyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Taikhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("BanDienThoai.Data.Chitietdonhang", b =>
                {
                    b.HasOne("BanDienThoai.Data.Donhang", "Donhang")
                        .WithMany("Chitietdonhang")
                        .HasForeignKey("DonhangId");

                    b.HasOne("BanDienThoai.Data.Sanpham", "Sanpham")
                        .WithMany("Chitietdonhang")
                        .HasForeignKey("SanphamID");

                    b.Navigation("Donhang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("BanDienThoai.Data.Chitietdonnhap", b =>
                {
                    b.HasOne("BanDienThoai.Data.Hoadonnhap", "Hoadonnhap")
                        .WithMany("Chitietdonnhap")
                        .HasForeignKey("HoadonnhapId");

                    b.HasOne("BanDienThoai.Data.Sanpham", "Sanpham")
                        .WithMany("Chitietdonnhap")
                        .HasForeignKey("SanphamID");

                    b.Navigation("Hoadonnhap");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("BanDienThoai.Data.Donhang", b =>
                {
                    b.HasOne("BanDienThoai.Data.Khachhang", "Khachhang")
                        .WithMany("Donhang")
                        .HasForeignKey("KhachhangId");

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("BanDienThoai.Data.Hoadonnhap", b =>
                {
                    b.HasOne("BanDienThoai.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("Hoadonnhap")
                        .HasForeignKey("NhaCungCapId");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("BanDienThoai.Data.Sanpham", b =>
                {
                    b.HasOne("BanDienThoai.Data.LoaiSp", "LoaiSp")
                        .WithMany("Sanpham")
                        .HasForeignKey("LoaiSpID");

                    b.Navigation("LoaiSp");
                });

            modelBuilder.Entity("BanDienThoai.Data.Donhang", b =>
                {
                    b.Navigation("Chitietdonhang");
                });

            modelBuilder.Entity("BanDienThoai.Data.Hoadonnhap", b =>
                {
                    b.Navigation("Chitietdonnhap");
                });

            modelBuilder.Entity("BanDienThoai.Data.Khachhang", b =>
                {
                    b.Navigation("Donhang");
                });

            modelBuilder.Entity("BanDienThoai.Data.LoaiSp", b =>
                {
                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("BanDienThoai.Data.NhaCungCap", b =>
                {
                    b.Navigation("Hoadonnhap");
                });

            modelBuilder.Entity("BanDienThoai.Data.Sanpham", b =>
                {
                    b.Navigation("Chitietdonhang");

                    b.Navigation("Chitietdonnhap");
                });
#pragma warning restore 612, 618
        }
    }
}
